#pragma once

// The chat log: a translucent panel in the bottom left with the last few lines
// the server sent.
//
// It exists to answer "is anything arriving" without reading a console, so it
// is deliberately plain - no scrollback, no input, no word wrap beyond a hard
// cut at the panel edge. The same one-triangle-and-discard approach the radar
// uses, for the same reason: a few hundred glyphs do not need a vertex buffer.

namespace mh
{
/// How many lines the panel holds. The oldest falls off the top.
inline constexpr int kChatLines = 8;

/// How many characters fit across. Anything longer is cut, which is honest
/// about being a monitor rather than a chat client.
inline constexpr int kChatColumns = 52;

inline constexpr const char* kChatShader = R"(
struct ChatUniforms {
    // Panel rectangle in normalised device coordinates: left, bottom, width,
    // height. Sized by the caller so the glyphs stay square whatever the
    // window shape.
    placement : vec4<f32>,
    // Lines in use, then the panel's opacity. The rest is spare.
    counts : vec4<f32>,
    // One character per vec4. A uniform array strides by 16 bytes whatever is
    // in it, so packing them tighter would buy nothing - the radar's zone
    // label learned this first.
    glyphs : array<vec4<f32>, 416>,
};

// The same 4x6 font the radar uses, generated by tools/radarfont.py.
// Index into " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'-."
const kGlyphWidth = 4;
const kGlyphHeight = 6;
const kColumns = 52;
const kChatLinesConst = 8;
const kFont = array<u32, 40>(
    0u, 16290430u, 6969727u, 8788062u, 8001663u, 8804735u, 283007u, 16144478u,
    16531775u, 139233u, 8263696u, 8725311u, 8521791u, 16540095u, 16613823u, 8001630u,
    1610367u, 12130398u, 10064511u, 6707554u, 270273u, 8259615u, 4131855u, 16614975u,
    13419315u, 806659u, 9329265u, 8018526u, 8648832u, 10132578u, 6969697u, 16531719u,
    6707559u, 6707550u, 842817u, 6969690u, 8034918u, 192u, 1065220u, 2048u
);

@group(0) @binding(0) var<uniform> chat : ChatUniforms;

struct VertexOut {
    @builtin(position) position : vec4<f32>,
    @location(0) ndc : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) index : u32) -> VertexOut {
    var corners = array<vec2<f32>, 3>(
        vec2<f32>(-1.0, -3.0),
        vec2<f32>(-1.0,  1.0),
        vec2<f32>( 3.0,  1.0));

    var out : VertexOut;
    out.ndc = corners[index];
    out.position = vec4<f32>(corners[index], 0.0, 1.0);
    return out;
}

@fragment
fn fragmentMain(in : VertexOut) -> @location(0) vec4<f32> {
    let left = chat.placement.x;
    let bottom = chat.placement.y;
    let width = chat.placement.z;
    let height = chat.placement.w;

    let local = vec2<f32>(in.ndc.x - left, in.ndc.y - bottom);
    if (local.x < 0.0 || local.x > width || local.y < 0.0 || local.y > height) {
        discard;
    }

    let lines = i32(chat.counts.x);
    let opacity = chat.counts.y;
    if (lines <= 0) {
        discard;
    }

    // Cell grid. Row 0 is the top line, and NDC y runs the other way.
    let cellWidth = width / f32(kColumns);
    let cellHeight = height / f32(kChatLinesConst);
    let column = i32(local.x / cellWidth);
    let row = kChatLinesConst - 1 - i32(local.y / cellHeight);

    var colour = vec3<f32>(0.04, 0.05, 0.07);

    if (row >= 0 && row < lines && column >= 0 && column < kColumns) {
        // Where we are inside this character cell, in glyph pixels. The glyph
        // is 4x6 in a cell with a little room around it so lines do not touch.
        let insideX = (local.x - f32(column) * cellWidth) / cellWidth;
        let insideY = 1.0 - (local.y - f32(kChatLinesConst - 1 - row) * cellHeight) / cellHeight;

        let gx = i32(insideX * f32(kGlyphWidth + 1));
        let gy = i32(insideY * f32(kGlyphHeight + 2)) - 1;

        if (gx >= 0 && gx < kGlyphWidth && gy >= 0 && gy < kGlyphHeight) {
            let glyph = kFont[i32(chat.glyphs[row * kColumns + column].x)];
            if (((glyph >> u32(gx * kGlyphHeight + gy)) & 1u) == 1u) {
                colour = vec3<f32>(0.92, 0.94, 0.98);
            }
        }
    }

    // A brighter edge along the top so the panel reads as a panel rather than
    // as a dark patch someone forgot to draw.
    if (local.y > height - 0.004) {
        colour = vec3<f32>(0.45, 0.50, 0.60);
    }

    return vec4<f32>(colour, opacity);
}
)";
} // namespace mh
