#pragma once

// The radar: a circular window onto the baked zone map, with whatever is
// nearby drawn on top.
//
// Everything happens in the fragment shader over one triangle. The dots could
// be instanced quads, but a radar shows a few dozen entities at most and a
// bounded loop needs no second pipeline, no vertex buffer and no draw call per
// entity.

namespace mh
{
/// How many entities the radar can show at once. The server only sends what is
/// in range, so this is a ceiling on a list that is usually far shorter.
inline constexpr int kRadarMaxEntities = 96;

/// How many characters of zone name fit along the bottom.
inline constexpr size_t kRadarMaxLabel = 24;

inline constexpr const char* kRadarShader = R"(
struct RadarUniforms {
    // Where the radar sits on screen and how big it is, in normalised device
    // coordinates, plus the aspect so the circle stays a circle.
    placement : vec4<f32>,      // centre x, centre y, radius, aspect
    // The square the map was baked over: centre x, centre z, half extent.
    mapExtent : vec4<f32>,
    // Who we are: world x, world z, heading in radians, radar range in units.
    viewer : vec4<f32>,
    // How many entity slots are in use, how many label characters, and
    // whether the map turns with the player rather than holding north up.
    counts : vec4<f32>,
    // The zone name, one character per vec4 - a uniform array strides by 16
    // bytes whatever is in it, so packing them tighter would buy nothing.
    label : array<vec4<f32>, 24>,
    // x, z, kind, unused. Kind: 0 player, 1 npc, 2 enemy.
    entities : array<vec4<f32>, 96>,
};

// 40 glyphs, 4x6, generated by tools/radarfont.py - the art lives there, as
// pictures that can be checked, rather than as hexadecimal here.
// Index into " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'-."
const kGlyphWidth = 4;
const kGlyphHeight = 6;
const kFont = array<u32, 40>(
    0u, 16290430u, 6969727u, 8788062u, 8001663u, 8804735u, 283007u, 16144478u,
    16531775u, 139233u, 8263696u, 8725311u, 8521791u, 16540095u, 16613823u, 8001630u,
    1610367u, 12130398u, 10064511u, 6707554u, 270273u, 8259615u, 4131855u, 16614975u,
    13419315u, 806659u, 9329265u, 8018526u, 8648832u, 10132578u, 6969697u, 16531719u,
    6707559u, 6707550u, 842817u, 6969690u, 8034918u, 192u, 1065220u, 2048u
);

@group(0) @binding(0) var<uniform> radar : RadarUniforms;
@group(0) @binding(1) var mapTexture : texture_2d<f32>;
@group(0) @binding(2) var maskTexture : texture_2d<f32>;
@group(0) @binding(3) var mapSampler : sampler;

struct VertexOut {
    @builtin(position) position : vec4<f32>,
    @location(0) ndc : vec2<f32>,
};

@vertex
fn vertexMain(@builtin(vertex_index) index : u32) -> VertexOut {
    // One oversized triangle covering the screen. The radar discards all of it
    // but its own corner, which costs less than it sounds - the rasteriser
    // rejects whole tiles at a time.
    var corners = array<vec2<f32>, 3>(
        vec2<f32>(-1.0, -3.0),
        vec2<f32>(-1.0,  1.0),
        vec2<f32>( 3.0,  1.0));

    var out : VertexOut;
    out.ndc = corners[index];
    out.position = vec4<f32>(corners[index], 0.0, 1.0);
    return out;
}

/// Where a point in the world lands in the baked map, as a texture coordinate.
/// The map is north up and east right, so z runs the opposite way to v.
fn mapUv(world : vec2<f32>) -> vec2<f32> {
    let half = radar.mapExtent.z;
    let u = (world.x - (radar.mapExtent.x - half)) / (half * 2.0);
    let v = ((radar.mapExtent.y + half) - world.y) / (half * 2.0);
    return vec2<f32>(u, v);
}

@fragment
fn fragmentMain(in : VertexOut) -> @location(0) vec4<f32> {
    let centre = radar.placement.xy;
    let radius = radar.placement.z;
    let aspect = radar.placement.w;

    // Into a space where the radar is a unit circle. x is divided by the
    // aspect so a round radar stays round on a wide window.
    var offset = (in.ndc - centre) / radius;
    offset.x = offset.x * aspect;

    let distance = length(offset);
    if (distance > 1.0) {
        discard;
    }

    // Radar space to world. y on screen is up, which is +z (north) with the
    // map held still, or the way the player is facing when it turns with them.
    //
    // Turning it here rather than anywhere else is what keeps the dots
    // honest: they are found by comparing world positions against this one, so
    // the map and everything on it turn together by construction.
    let heading = radar.viewer.z;
    let turning = radar.counts.z > 0.5;
    var sampled = offset;
    if (turning) {
        // Sends screen-up to the direction faced, so what is ahead is at the
        // top of the circle.
        let c = cos(heading);
        let s = sin(heading);
        sampled = vec2<f32>(offset.x * c + offset.y * s,
                            -offset.x * s + offset.y * c);
    }

    let range = radar.viewer.w;
    let world = vec2<f32>(radar.viewer.x + sampled.x * range,
                          radar.viewer.y + sampled.y * range);

    let uv = mapUv(world);
    var colour = vec3<f32>(0.04, 0.05, 0.07);
    if (uv.x >= 0.0 && uv.x <= 1.0 && uv.y >= 0.0 && uv.y <= 1.0) {
        // textureSampleLevel, not textureSample: the discard above makes
        // control flow non-uniform, and implicit derivatives are illegal
        // there. The map has no mipmaps anyway.
        let terrain = textureSampleLevel(mapTexture, mapSampler, uv, 0.0).rgb;
        let walkable = textureSampleLevel(maskTexture, mapSampler, uv, 0.0).r;

        // Blocked ground is pushed down and desaturated; walkable ground is
        // left alone.
        //
        // The first attempt lifted the walkable side instead, which looked
        // right in a field and destroyed a town - almost all of Bastok is
        // walkable, so tinting it turned the whole map one flat colour and
        // lost the streets. Darkening the exception keeps the map legible
        // wherever the balance happens to fall.
        let flat = vec3<f32>(dot(terrain, vec3<f32>(0.299, 0.587, 0.114)));
        colour = mix(flat * 0.30, terrain, walkable);
    }

    // Range rings, every quarter of the radar, as a sense of distance.
    let ring = fract(distance * 4.0);
    if (ring < 0.03 && distance > 0.05) {
        colour = mix(colour, vec3<f32>(0.75, 0.80, 0.85), 0.18);
    }

    // Entities. Nearest wins, so a dot on top of another is still one dot
    // rather than a blend of two colours that reads as a third kind.
    // Smaller than they were, and ringed in black. A dot has to read as a
    // dot against grass, stone, water and a dark interior, and size was doing
    // the work an outline does better - two of them close together used to
    // merge into one blob.
    let dotRadius = range * 0.030;
    let outlineRadius = dotRadius * 1.7;
    // Searched to the outline rather than the fill, or the ring would be
    // clipped to the dot it is meant to surround.
    var best = outlineRadius;
    var dot = vec3<f32>(0.0);
    var found = false;

    let count = i32(radar.counts.x);
    for (var i = 0; i < count; i = i + 1) {
        let entity = radar.entities[i];
        let away = length(vec2<f32>(entity.x, entity.y) - world);
        if (away < best) {
            best = away;
            found = true;
            let kind = i32(entity.z);
            if (kind == 0) {
                dot = vec3<f32>(0.25, 0.62, 1.00);   // player
            } else if (kind == 2) {
                dot = vec3<f32>(0.95, 0.26, 0.24);   // enemy
            } else {
                dot = vec3<f32>(0.24, 0.92, 0.36);   // npc
            }
        }
    }
    if (found) {
        // Black first, then the colour inside it, so the ring is a ring rather
        // than a darkening of whatever happens to be underneath.
        let ring = smoothstep(outlineRadius, outlineRadius * 0.80, best);
        colour = mix(colour, vec3<f32>(0.0, 0.0, 0.0), ring);
        let fill = smoothstep(dotRadius, dotRadius * 0.65, best);
        colour = mix(colour, dot, fill);
    }

    // Us, at the centre, with a notch showing which way we face. With the
    // map turning, that is always straight up - which is the point of it.
    //
    // Orange, and the only orange thing on the radar: at a glance the question
    // is where am I, and a white dot among white range rings answers it more
    // slowly than a colour nothing else uses.
    let facing = select(vec2<f32>(sin(heading), cos(heading)), vec2<f32>(0.0, 1.0), turning);
    // Not `self`: that is a reserved word in WGSL, and naming a variable
    // with one fails the whole module rather than the line - which takes the
    // pipeline, and every pass that shares it, down to a black window. The
    // same trap as `target`, which cost an evening once already.
    let ownDot = vec3<f32>(1.00, 0.58, 0.13);
    if (distance < 0.075) {
        colour = mix(colour, vec3<f32>(0.0, 0.0, 0.0), smoothstep(0.075, 0.060, distance));
    }
    if (distance < 0.055) {
        colour = ownDot;
    } else if (distance < 0.13 && dot2(normalize(offset), facing) > 0.86) {
        colour = ownDot;
    }

    // A rim around the whole thing, so it reads as an instrument rather than a
    // hole cut in the view.
    let rim = smoothstep(0.94, 1.0, distance);
    colour = mix(colour, vec3<f32>(0.82, 0.86, 0.92), rim);

    // The zone name, centred along the bottom. Drawn inside the circle rather
    // than under it so the radar stays one object.
    let letters = i32(radar.counts.y);
    if (letters > 0) {
        // Sized to fit the chord at the baseline, not a fixed size. The
        // circle is 1.5 wide where the text sits, and a zone name can be
        // anything from "BASTOK" to "EAST SARUTABARUTA" - at one scale the
        // long ones run out of the circle and the ends simply vanish, because
        // everything outside it is discarded.
        let widest = 1.30;
        let perGlyph = f32(kGlyphWidth + 1);
        let scale = min(0.030, widest / (f32(letters) * perGlyph));
        let advance = perGlyph * scale;
        let textWidth = f32(letters) * advance;
        let left = -textWidth * 0.5;
        let baseline = 0.66;                     // down from the middle

        let local = vec2<f32>(offset.x - left, offset.y + baseline);
        if (local.x >= 0.0 && local.x < textWidth && local.y >= 0.0 &&
            local.y < f32(kGlyphHeight) * scale) {
            let index = i32(local.x / advance);
            let column = i32((local.x - f32(index) * advance) / scale);
            // Row 0 is the top of the glyph, and screen y runs the other way.
            let row = kGlyphHeight - 1 - i32(local.y / scale);

            if (index < letters && column < kGlyphWidth) {
                let glyph = kFont[i32(radar.label[index].x)];
                if ((glyph >> u32(column * kGlyphHeight + row)) & 1u) == 1u {
                    colour = vec3<f32>(0.96, 0.97, 1.0);
                } else {
                    colour = colour * 0.45;
                }
            }
        }
    }

    return vec4<f32>(colour, 0.88);
}

fn dot2(a : vec2<f32>, b : vec2<f32>) -> f32 {
    return a.x * b.x + a.y * b.y;
}
)";
} // namespace mh
