# Builds the text atlas the renderer draws names, chat and the zone label with.
#
#   powershell -ExecutionPolicy Bypass -File tools\makefont.ps1
#
# Writes renderer/assets/font.png and renderer/assets/font.txt.
#
# Two coverages per texel rather than one: red is the glyph, green is the
# outline around it. That keeps the colour decision in the shader, so a name
# can be tinted per role - party, linkshell, GM - while its outline stays
# black, without a second atlas or a second draw.
#
# The alternative, baking white-on-black glyphs, fixes the colour at bake time
# and makes every tint wrong at the edges.
param(
    [string]$Family = "Verdana",
    [int]$Cell = 64,
    [int]$Size = 40,
    [single]$OutlineWidth = 5.0,   # centred on the path, so about half shows
    [string]$OutDir = ""
)

Add-Type -AssemblyName System.Drawing

if (-not $OutDir) {
    $OutDir = Join-Path (Split-Path -Parent $PSScriptRoot) "renderer\assets"
}
[void](New-Item -ItemType Directory -Force -Path $OutDir)

# Printable ASCII. FFXI names are ASCII, and so is everything else this draws.
$first = 32
$last = 126
$count = $last - $first + 1
$columns = 16
$rows = [math]::Ceiling($count / $columns)

$width = $columns * $Cell
$height = $rows * $Cell

$bmp = New-Object System.Drawing.Bitmap($width, $height, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::FromArgb(0, 0, 0, 0))
$g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias

$font = New-Object System.Drawing.Font($Family, $Size, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
$outlinePen = New-Object System.Drawing.Pen([System.Drawing.Color]::FromArgb(255, 0, 255, 0), $OutlineWidth)
$outlinePen.LineJoin = [System.Drawing.Drawing2D.LineJoin]::Round
$fillBrush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255, 255, 0, 0))

$metrics = New-Object System.Collections.Generic.List[string]
$metrics.Add("# glyph atlas for MogHouse - generated by tools/makefont.ps1")
$metrics.Add("# family $Family bold, cell $Cell, pixel size $Size, outline $OutlineWidth")
$metrics.Add("# atlas $width $height, first char $first, columns $columns")
$metrics.Add("atlas $width $height $Cell $columns $first $count")

# Measured in a scratch context: StringFormat.GenericTypographic reports the
# advance without the padding DrawString adds on its own.
$format = [System.Drawing.StringFormat]::GenericTypographic.Clone()
$format.FormatFlags = $format.FormatFlags -bor [System.Drawing.StringFormatFlags]::MeasureTrailingSpaces

for ($i = 0; $i -lt $count; $i++) {
    $code = $first + $i
    $ch = [char]$code
    $col = $i % $columns
    $row = [math]::Floor($i / $columns)

    # A little in from the cell corner so the outline has somewhere to go.
    $x = $col * $Cell + $OutlineWidth
    $y = $row * $Cell + $OutlineWidth

    $path = New-Object System.Drawing.Drawing2D.GraphicsPath
    $path.AddString([string]$ch, $font.FontFamily, [int]$font.Style, $Size, (New-Object System.Drawing.PointF($x, $y)), $format)

    # Outline first, then the glyph over it, so red is the interior only.
    $g.DrawPath($outlinePen, $path)
    $g.FillPath($fillBrush, $path)
    $path.Dispose()

    $advance = $g.MeasureString([string]$ch, $font, [System.Drawing.PointF]::Empty, $format).Width
    $metrics.Add(("glyph {0} {1:F3}" -f $code, $advance))
}

$g.Dispose()
$bmp.Save((Join-Path $OutDir "font.png"), [System.Drawing.Imaging.ImageFormat]::Png)

# And raw BGRA, because the renderer has decoders for FFXI's own texture
# formats and nothing else. A PNG here would mean carrying a PNG decoder for
# one file.
$rect = New-Object System.Drawing.Rectangle(0, 0, $width, $height)
$data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$bytes = New-Object byte[] ($data.Stride * $height)
[System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bytes, 0, $bytes.Length)
$bmp.UnlockBits($data)
[System.IO.File]::WriteAllBytes((Join-Path $OutDir "font.bin"), $bytes)

$bmp.Dispose()
$font.Dispose()
$outlinePen.Dispose()
$fillBrush.Dispose()

Set-Content -Path (Join-Path $OutDir "font.txt") -Value $metrics -Encoding ascii
Write-Output "wrote $OutDir\font.png ($width x $height) and font.txt ($count glyphs)"
