"""Generates the tiny bitmap font the radar labels itself with.

The renderer has no font system and does not want one for a single line of
text. This turns readable ASCII art into the packed constants
renderer/radar_shader.h uses, so the glyphs stay editable as pictures rather
than as hexadecimal nobody can check.

Each glyph is 4 wide and 6 tall, packed into one u32: bit (column * 6 + row),
row 0 at the top.

    python tools/radarfont.py        prints the WGSL array
"""

WIDTH = 4
HEIGHT = 6

# Uppercase only, plus the punctuation that turns up in FFXI zone names.
GLYPHS = {
    " ": ["....", "....", "....", "....", "....", "...."],
    "A": [".##.", "#..#", "#..#", "####", "#..#", "#..#"],
    "B": ["###.", "#..#", "###.", "#..#", "#..#", "###."],
    "C": [".###", "#...", "#...", "#...", "#...", ".###"],
    "D": ["###.", "#..#", "#..#", "#..#", "#..#", "###."],
    "E": ["####", "#...", "###.", "#...", "#...", "####"],
    "F": ["####", "#...", "###.", "#...", "#...", "#..."],
    "G": [".###", "#...", "#.##", "#..#", "#..#", ".###"],
    "H": ["#..#", "#..#", "####", "#..#", "#..#", "#..#"],
    "I": ["###.", ".#..", ".#..", ".#..", ".#..", "###."],
    "J": ["..##", "...#", "...#", "...#", "#..#", ".##."],
    "K": ["#..#", "#.#.", "##..", "##..", "#.#.", "#..#"],
    "L": ["#...", "#...", "#...", "#...", "#...", "####"],
    "M": ["#..#", "####", "####", "#..#", "#..#", "#..#"],
    "N": ["#..#", "##.#", "##.#", "#.##", "#.##", "#..#"],
    "O": [".##.", "#..#", "#..#", "#..#", "#..#", ".##."],
    "P": ["###.", "#..#", "#..#", "###.", "#...", "#..."],
    "Q": [".##.", "#..#", "#..#", "#..#", "#.#.", ".#.#"],
    "R": ["###.", "#..#", "#..#", "###.", "#.#.", "#..#"],
    "S": [".###", "#...", ".##.", "...#", "...#", "###."],
    "T": ["####", ".#..", ".#..", ".#..", ".#..", ".#.."],
    "U": ["#..#", "#..#", "#..#", "#..#", "#..#", ".##."],
    "V": ["#..#", "#..#", "#..#", "#..#", ".##.", ".##."],
    "W": ["#..#", "#..#", "#..#", "####", "####", "#..#"],
    "X": ["#..#", "#..#", ".##.", ".##.", "#..#", "#..#"],
    "Y": ["#..#", "#..#", ".##.", ".#..", ".#..", ".#.."],
    "Z": ["####", "...#", "..#.", ".#..", "#...", "####"],
    "0": [".##.", "#..#", "#.##", "##.#", "#..#", ".##."],
    "1": ["..#.", ".##.", "..#.", "..#.", "..#.", ".###"],
    "2": [".##.", "#..#", "...#", "..#.", ".#..", "####"],
    "3": ["###.", "...#", ".##.", "...#", "...#", "###."],
    "4": ["#..#", "#..#", "####", "...#", "...#", "...#"],
    "5": ["####", "#...", "###.", "...#", "...#", "###."],
    "6": [".###", "#...", "###.", "#..#", "#..#", ".##."],
    "7": ["####", "...#", "..#.", "..#.", ".#..", ".#.."],
    "8": [".##.", "#..#", ".##.", "#..#", "#..#", ".##."],
    "9": [".##.", "#..#", "#..#", ".###", "...#", "###."],
    "'": [".#..", ".#..", "....", "....", "....", "...."],
    "-": ["....", "....", "####", "....", "....", "...."],
    ".": ["....", "....", "....", "....", "....", ".#.."],
}

# The order the shader indexes by. Anything outside it renders as a space.
ORDER = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'-."


def pack(art):
    assert len(art) == HEIGHT, "wrong height"
    bits = 0
    for row, line in enumerate(art):
        assert len(line) == WIDTH, f"wrong width: {line!r}"
        for column, cell in enumerate(line):
            if cell == "#":
                bits |= 1 << (column * HEIGHT + row)
    return bits


def main():
    values = [pack(GLYPHS[character]) for character in ORDER]

    print(f"// {len(values)} glyphs, {WIDTH}x{HEIGHT}, generated by tools/radarfont.py.")
    print(f"// Index into ORDER: {ORDER!r}")
    print(f"const kGlyphCount = {len(values)};")
    print(f"const kFont = array<u32, {len(values)}>(")
    for start in range(0, len(values), 8):
        row = ", ".join(f"{value}u" for value in values[start:start + 8])
        end = "," if start + 8 < len(values) else ""
        print(f"    {row}{end}")
    print(");")


if __name__ == "__main__":
    main()
